spring:
  application.name: content-share
  threads.virtual.enabled: true

content-share:
  send-directory: ${SEND_DIRECTORY:send}
  receive-directory: ${RECEIVE_DIRECTORY:receive}
  base-url: ${BASE_URL:http://localhost:8080}